services:
  ipindex-node:
    build:
      dockerfile: node.Dockerfile
      context: .
    volumes:
      - .:/var/www

  ipindex-nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
