name: Build database
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Installing deps
        run: pip install -r requirements.txt
      - name: Build
        run: python src/main.py
      - name: Test
        run: python src/example.py
      - uses: EndBug/add-and-commit@v4
        with:
          add: .
          message: Updated database
      - name: Push changes and the new tag
        run: git push --follow-tags